version: '3.8'

services:
  manu-project-fe:
    container_name: manu-project-fe
    build:
      context: .
      dockerfile: dockerfile
#    ports:
#      - "3002:80"
    restart: unless-stopped
    networks:
      - bible-project-network

networks:
  bible-project-network:
    external: true
