version: '3.3'

services: 
  backend_nest_server:
    container_name: nest_server
    build: 
      context: .
      dockerfile: DockerNest
    working_dir: /nest_angular_app
    environment: 
      - JWT_SECRET=${JWT_SECRET}
      - EmailFromUserName=${EmailFromUserName}
      - EmailPassword=${EmailPassword}
      - EmailToUserName=${EmailToUserName}
      - EmailUserName=${EmailUserName}
    # ports: 
    #   - 8080:4200
    # user: ${CURRENT_UID}
    volumes: 
      - ..:/nest_angular_app
    networks:
      - manuapp_network
    entrypoint: "npm run serve"
  frontend_angular_server:
    container_name: angular_server
    build: 
      context: .
      dockerfile: DockerAngular
    working_dir: /angular_app
    # ports: 
    #   - 4000:4200
    volumes:
      - ..:/angular_app
    networks:
      - manuapp_network
    entrypoint: "sleep 100"
    # entrypoint: "ng serve --host 0.0.0.0"
  # ng_inx_server:
  #   container_name: nginx_server
  #   build: 
  #     context: ./nginx
  #     dockerfile: dockerfile
  #   ports: 
  #     - 80:80
  #   volumes: 
  #     - ./nginx/conf.d:/etc/nginx/conf.d
  #   command: /bin/bash -c "nginx -g 'daemon off;'"
  #   networks:
  #     - manuapp_network
    

networks:
  manuapp_network: